# Generated by Django 3.1 on 2020-08-24 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200824_1251'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='statu',
        ),
    ]
