# Generated by Django 3.1 on 2020-08-24 05:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200824_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='statu',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statu',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='statu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statu',
            name='title',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
