# Generated by Django 3.1 on 2020-08-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200824_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('statu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.statu')),
            ],
        ),
    ]
