# Generated by Django 3.1 on 2020-08-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
