# Generated by Django 3.1 on 2020-08-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statu',
            old_name='title',
            new_name='topic',
        ),
    ]
