# Generated by Django 3.1 on 2020-08-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200824_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statu',
            name='datatype',
            field=models.TextField(blank=True, max_length=3),
        ),
    ]
