# Generated by Django 3.1 on 2020-09-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200831_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statu',
            name='changed_at',
        ),
        migrations.RemoveField(
            model_name='statu',
            name='created_at',
        ),
        migrations.AddField(
            model_name='statu',
            name='download',
            field=models.TextField(blank=True),
        ),
    ]
