# Generated by Django 3.1 on 2020-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200901_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=70)),
                ('datatype', models.TextField(blank=True, max_length=3)),
                ('QOS', models.CharField(default=0, max_length=2)),
                ('download', models.TextField(blank=True, max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='statu',
        ),
    ]
