# Generated by Django 3.1 on 2020-09-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200901_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='download',
            field=models.URLField(blank=True),
        ),
    ]
