# Generated by Django 3.1 on 2020-09-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200901_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='content',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='download',
        ),
    ]
