# Generated by Django 3.1 on 2020-10-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20200901_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='QOS',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='datatype',
        ),
    ]
